#!/usr/bin/env python

from distutils.core import setup

import py2exe

setup(windows = ["play.py"],
      # console = ["play.py"],
      name = "rpg-world",
      version = "1.0",
      packages=["rpg"],
      author="Sam Eldred",
      author_email="samuel.eldred@gmail.com",
      url="http://code.google.com/p/rpg-world/",
      license="GNU GPL v3",
      description="Game/game engine written in Python/Pygame",
      long_description="""16-bit style graphics, a top-down perspective and tile-based maps - a
          retro style RPG much like the old SNES classics. Also features some pseudo-3D elements,
          eg. the ability to move underneath bridges, etc.""",
      platforms="Python source code",
      data_files=[("images", ["images/font-black.png",
                              "images/font-white.png",
                              "images/horizon.png",
                              "images/numbers.png",
                              "images/title.png"]),
                  ("maps", ["maps/drops.map",
                            "maps/forest.map",
                            "maps/lowercave.map",
                            "maps/skullcave.map",
                            "maps/smallcave.map",
                            "maps/start.map",
                            "maps/uppercave.map"]),
                  ("music", ["music/ulmo-main.ogg",
                             "music/ulmo-title.ogg"]),
                  ("sounds", ["sounds/beetle.wav",
                              "sounds/blades.wav",
                              "sounds/checkpoint.wav",
                              "sounds/door.wav",
                              "sounds/endgame.wav",
                              "sounds/falling.wav",
                              "sounds/footstep.wav",
                              "sounds/lifelost.wav",
                              "sounds/pickup.wav",
                              "sounds/swoosh.wav",
                              "sounds/title.wav",
                              "sounds/wasp.wav",
                              "sounds/waves.wav"]),
                  ("sprites", ["sprites/beetle-frames.png",
                               "sprites/blades-frames.png",
                               "sprites/boat.png",
                               "sprites/check-frames.png",
                               "sprites/chest.png",
                               "sprites/coin-frames.png",
                               "sprites/door-frames.png",
                               "sprites/flame-frames.png",
                               "sprites/key-frames.png",
                               "sprites/life.png",
                               "sprites/rock.png",
                               "sprites/shadow.png",
                               "sprites/small-check.png",
                               "sprites/small-coin.png",
                               "sprites/small-key.png",
                               "sprites/ulmo-falling.png",
                               "sprites/ulmo-frames.png",
                               "sprites/wasp-frames.png"]),
                  ("tiles", ["tiles/dungeon_metadata.txt",
                             "tiles/dungeon.png",
                             "tiles/earth_metadata.txt",
                             "tiles/earth.png",
                             "tiles/grass_metadata.txt",
                             "tiles/grass.png",
                             "tiles/objects_metadata.txt",
                             "tiles/objects.png",
                             "tiles/water_metadata.txt",
                             "tiles/water.png",
                             "tiles/wood_metadata.txt",
                             "tiles/wood.png"])]
)
